import z3

WORKSPACE = dict()

WORKSPACE[1] = {'type': z3.String, 'default': "Windows (64-bit) NT :.00"}
WORKSPACE[2] = {'type': z3.Int, 'default': 16}
WORKSPACE[3] = {'type': z3.Real, 'default': 0}
WORKSPACE[4] = {'type': z3.Bool, 'default': False}
WORKSPACE[5] = {'type': z3.Bool, 'default': True}
WORKSPACE[6] = {'type': z3.Bool, 'default': True}
WORKSPACE[7] = {'type': z3.Bool, 'default': True}
WORKSPACE[8] = {'type': z3.Bool, 'default': True}
WORKSPACE[9] = {'type': z3.String, 'default': "/"}
WORKSPACE[10] = {'type': z3.Real, 'default': 0}
WORKSPACE[11] = {'type': z3.Real, 'default': -5}
WORKSPACE[12] = {'type': z3.Real, 'default': -6}
WORKSPACE[13] = {'type': z3.Int, 'default': 700}
WORKSPACE[14] = {'type': z3.Int, 'default': 480}
WORKSPACE[15] = {'type': z3.Real, 'default': 3}
WORKSPACE[16] = {'type': z3.String, 'default': ""}
WORKSPACE[17] = {'type': z3.String, 'default': ""}
WORKSPACE[18] = {'type': z3.Bool, 'default': True}
WORKSPACE[19] = {'type': z3.Bool, 'default': True}
WORKSPACE[20] = {'type': z3.String, 'default': ""}
WORKSPACE[21] = {'type': z3.Bool, 'default': True}
WORKSPACE[22] = {'type': z3.Real, 'default': 0}
WORKSPACE[23] = {'type': z3.String, 'default': "C:\\Users\\user\\AppData\\Roaming\\Microsoft\\Excel\\XLSTART"}
WORKSPACE[24] = {'type': z3.String, 'default': ""}
WORKSPACE[25] = {'type': z3.Bool, 'default': False}
WORKSPACE[26] = {'type': z3.String, 'default': "Windows User"}
WORKSPACE[27] = {'type': z3.String, 'default': ""}
WORKSPACE[28] = {'type': z3.Real, 'default': 1}
WORKSPACE[29] = {'type': z3.Bool, 'default': False}
WORKSPACE[30] = {'type': z3.String, 'default': ""}
WORKSPACE[31] = {'type': z3.Bool, 'default': False}
WORKSPACE[32] = {'type': z3.String, 'default': "C:\\Program Files\\Microsoft Office\\Office16"}
WORKSPACE[33] = {'type': z3.String, 'default': "Worksheet"}
WORKSPACE[34] = {'type': z3.String, 'default': ""}
WORKSPACE[35] = {'type': z3.Bool, 'default': False}
WORKSPACE[36] = {'type': z3.Bool, 'default': True}
WORKSPACE[37] = {'type': z3.Real, 'default': 1}
WORKSPACE[38] = {'type': z3.Real, 'default': 1}
WORKSPACE[39] = {'type': z3.String, 'default': ""}
WORKSPACE[40] = {'type': z3.Bool, 'default': True}
WORKSPACE[41] = {'type': z3.String, 'default': ""}
WORKSPACE[42] = {'type': z3.Bool, 'default': True}
WORKSPACE[43] = {'type': z3.Bool, 'default': True}
WORKSPACE[44] = {'type': z3.String, 'default': ""}
WORKSPACE[45] = {'type': z3.Bool, 'default': False}
WORKSPACE[46] = {'type': z3.Bool, 'default': True}
WORKSPACE[47] = {'type': z3.String, 'default': ""}
WORKSPACE[48] = {'type': z3.String, 'default': "C:\\Program Files\\Microsoft Office\\Office16\\LIBRARY"}
WORKSPACE[49] = {'type': z3.String, 'default': ""}
WORKSPACE[50] = {'type': z3.Bool, 'default': False}
WORKSPACE[51] = {'type': z3.Bool, 'default': False}
WORKSPACE[52] = {'type': z3.Bool, 'default': False}
WORKSPACE[53] = {'type': z3.String, 'default': ""}
WORKSPACE[54] = {'type': z3.Bool, 'default': True}
WORKSPACE[55] = {'type': z3.Bool, 'default': True}
WORKSPACE[56] = {'type': z3.String, 'default': "Calibri"}
WORKSPACE[57] = {'type': z3.Real, 'default': 11}
WORKSPACE[58] = {'type': z3.Bool, 'default': True}
WORKSPACE[59] = {'type': z3.Bool, 'default': False}
WORKSPACE[60] = {'type': z3.Bool, 'default': False}
WORKSPACE[61] = {'type': z3.Real, 'default': 4}
WORKSPACE[62] = {'type': z3.String, 'default': ""}
WORKSPACE[63] = {'type': z3.Real, 'default': 1}
WORKSPACE[64] = {'type': z3.Bool, 'default': True}
WORKSPACE[65] = {'type': z3.Bool, 'default': True}
WORKSPACE[66] = {'type': z3.Real, 'default': 1}
WORKSPACE[67] = {'type': z3.String, 'default': "C:\\Users\\user\\Documents"}
WORKSPACE[68] = {'type': z3.Bool, 'default': True}
WORKSPACE[69] = {'type': z3.Bool, 'default': True}
WORKSPACE[70] = {'type': z3.Bool, 'default': False}
WORKSPACE[71] = {'type': z3.Bool, 'default': False}
WORKSPACE[72] = {'type': z3.Bool, 'default': True}
